# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0002_userprofile_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Bio',
            field=models.TextField(default='', max_length=140),
        ),
    ]
