# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0009_auto_20181010_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
