# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0010_userprofile_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(default='Garu/Natinga', max_length=100),
        ),
    ]
