# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-16 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0011_auto_20181015_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
