# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0013_auto_20181104_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
