# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
