# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-10 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181110_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='post_pictures'),
        ),
    ]
