# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181110_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='post_pictures'),
        ),
    ]
