# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='WhatsApp',
            field=models.IntegerField(default=0),
        ),
    ]
