# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendz', '0003_auto_20180424_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
